# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import resilience_pb2 as resilience__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resilience_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResiliencePeerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitEvidence = channel.unary_unary(
                '/resilience.v1.ResiliencePeer/SubmitEvidence',
                request_serializer=resilience__pb2.SignedEnvelope.SerializeToString,
                response_deserializer=resilience__pb2.Ack.FromString,
                _registered_method=True)
        self.SubmitVote = channel.unary_unary(
                '/resilience.v1.ResiliencePeer/SubmitVote',
                request_serializer=resilience__pb2.SignedEnvelope.SerializeToString,
                response_deserializer=resilience__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/resilience.v1.ResiliencePeer/Ping',
                request_serializer=resilience__pb2.PingRequest.SerializeToString,
                response_deserializer=resilience__pb2.PingReply.FromString,
                _registered_method=True)
        self.Investigate = channel.unary_unary(
                '/resilience.v1.ResiliencePeer/Investigate',
                request_serializer=resilience__pb2.SignedEnvelope.SerializeToString,
                response_deserializer=resilience__pb2.InvestigateResult.FromString,
                _registered_method=True)


class ResiliencePeerServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Investigate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResiliencePeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEvidence,
                    request_deserializer=resilience__pb2.SignedEnvelope.FromString,
                    response_serializer=resilience__pb2.Ack.SerializeToString,
            ),
            'SubmitVote': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitVote,
                    request_deserializer=resilience__pb2.SignedEnvelope.FromString,
                    response_serializer=resilience__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=resilience__pb2.PingRequest.FromString,
                    response_serializer=resilience__pb2.PingReply.SerializeToString,
            ),
            'Investigate': grpc.unary_unary_rpc_method_handler(
                    servicer.Investigate,
                    request_deserializer=resilience__pb2.SignedEnvelope.FromString,
                    response_serializer=resilience__pb2.InvestigateResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resilience.v1.ResiliencePeer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resilience.v1.ResiliencePeer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResiliencePeer:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resilience.v1.ResiliencePeer/SubmitEvidence',
            resilience__pb2.SignedEnvelope.SerializeToString,
            resilience__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resilience.v1.ResiliencePeer/SubmitVote',
            resilience__pb2.SignedEnvelope.SerializeToString,
            resilience__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resilience.v1.ResiliencePeer/Ping',
            resilience__pb2.PingRequest.SerializeToString,
            resilience__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Investigate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resilience.v1.ResiliencePeer/Investigate',
            resilience__pb2.SignedEnvelope.SerializeToString,
            resilience__pb2.InvestigateResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
